//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JaizAgencyBanking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BIODATA
    {
        public int SN { get; set; }
        public decimal CUSTOMERID { get; set; }
        public string BIOMETRICID { get; set; }
        public System.DateTime ENTRYDATE { get; set; }
        public string BANKCODE { get; set; }
        public string USERID { get; set; }
        public string ENTRYMODE { get; set; }
        public Nullable<int> TICKETID { get; set; }
        public string PHONENO { get; set; }
        public string BRANCH { get; set; }
        public string ENROLLMENTOFFICER { get; set; }
        public string ENROLLMENTIP { get; set; }
        public Nullable<System.DateTime> REGISTRATIONDATE { get; set; }
    }
}
