
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace JaizAgencyBanking.Models
{

using System;
    using System.Collections.Generic;
    
public partial class CategoryBill
{

    public int BillerID { get; set; }

    public string BillerName { get; set; }

    public int BillerCategoryId { get; set; }

    public string ReferenceDetails { get; set; }

    public string BillerCategoryName { get; set; }

}

}
