
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace JaizAgencyBanking.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Item
{

    public int ID { get; set; }

    public int ProviderRecognizedItemId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string ConsumerIdField { get; set; }

    public string Code { get; set; }

    public string Amount { get; set; }

    public decimal ConvertedAmount { get; set; }

    public int BillID { get; set; }

    public bool IsAmountFixed { get; set; }

    public int SortOrder { get; set; }

    public int PictureId { get; set; }

    public string PaymentCode { get; set; }

    public Nullable<decimal> MiniAmount { get; set; }

    public Nullable<decimal> MaxAmount { get; set; }

    public bool IsVisible { get; set; }

}

}
