
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace JaizAgencyBanking.Models
{

using System;
    using System.Collections.Generic;
    
public partial class log
{

    public long logID { get; set; }

    public System.DateTime logDate { get; set; }

    public string logIP { get; set; }

    public string logXML { get; set; }

    public Nullable<System.DateTime> logXMLOutDate { get; set; }

    public string logXMLOut { get; set; }

    public string methodName { get; set; }

}

}
