
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace JaizAgencyBanking.Models
{

using System;
    using System.Collections.Generic;
    
public partial class otprequest
{

    public int otpRequestID { get; set; }

    public System.DateTime otpDate { get; set; }

    public string otpPhone { get; set; }

    public string otpAccountNo { get; set; }

    public System.DateTime otpExpiry { get; set; }

    public string otp { get; set; }

}

}
