
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace JaizAgencyBanking.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TBFIList
{

    public long SN { get; set; }

    public Nullable<int> FIListDetailSN { get; set; }

    public string InstitutionCode { get; set; }

    public string InstitutionName { get; set; }

    public string Category { get; set; }

    public string LongInstitutionName { get; set; }

    public string OldInstitutionCode { get; set; }

    public short statusID { get; set; }

}

}
