
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace JaizAgencyBanking.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TransType
{

    public int typeID { get; set; }

    public decimal typeAmount { get; set; }

    public string transType1 { get; set; }

    public string transName { get; set; }

    public Nullable<int> channelCode { get; set; }

}

}
