
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace JaizAgencyBanking.Models
{

using System;
    using System.Collections.Generic;
    
public partial class vend
{

    public int airtimeVendID { get; set; }

    public int catID { get; set; }

    public string serviceID { get; set; }

    public string airtimeVendName { get; set; }

    public decimal amount { get; set; }

}

}
