
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace JaizAgencyBanking.Models
{

using System;
    using System.Collections.Generic;
    
public partial class vendingcat
{

    public int vendingID { get; set; }

    public string vendName { get; set; }

    public string serviceID { get; set; }

    public Nullable<int> vendType { get; set; }

}

}
