//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JaizAgencyBanking.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.18.192.100/bvn/bvnValidation")]
        public string JaizOpenDigitalBanking_NIBSSBVN_BVNValidation {
            get {
                return ((string)(this["JaizOpenDigitalBanking_NIBSSBVN_BVNValidation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.13.21.63/JaizNIBSSInterfaceSSM/processmessage.asmx")]
        public string JaizOpenDigitalBanking_NIBSS_processmessage {
            get {
                return ((string)(this["JaizOpenDigitalBanking_NIBSS_processmessage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://orion.interswitchng.com/quicktellerservice/QuickTeller.svc")]
        public string JaizOpenDigitalBanking_Quickteller_QuickTellerService {
            get {
                return ((string)(this["JaizOpenDigitalBanking_Quickteller_QuickTellerService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.234.10.104:8080/bvnV/bvnV")]
        public string JaizOpenDigitalBanking_BVNNibss_BVNValidationWebService {
            get {
                return ((string)(this["JaizOpenDigitalBanking_BVNNibss_BVNValidationWebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.13.21.63:8000/JaizNIBSSInterface/processmessage.asmx")]
        public string JaizOpenDigitalBanking_JaizNIBSSInterface_processmessage {
            get {
                return ((string)(this["JaizOpenDigitalBanking_JaizNIBSSInterface_processmessage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.13.21.63:8000/JaizInternal/processmessage.asmx")]
        public string JaizOpenDigitalBanking_JaizInternal_processmessage {
            get {
                return ((string)(this["JaizOpenDigitalBanking_JaizInternal_processmessage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.13.21.63:8000/JaizNIBSSInterface/processmessage.asmx")]
        public string JaizOpenDigitalBanking_NewNIP_processmessage {
            get {
                return ((string)(this["JaizOpenDigitalBanking_NewNIP_processmessage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.13.21.160:8013/JaizInternetBankingApi/JaizHelper.svc")]
        public string JaizOpenDigitalBanking_InzternetBankingAPI_JaizHelper {
            get {
                return ((string)(this["JaizOpenDigitalBanking_InzternetBankingAPI_JaizHelper"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.13.21.63:8000/JaizNIBSSOthers/processmessage.asmx")]
        public string JaizOpenDigitalBanking_JaizNIBSSOthers_processmessage {
            get {
                return ((string)(this["JaizOpenDigitalBanking_JaizNIBSSOthers_processmessage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://172.13.21.160:8013/JaizService/Controllers/JaizHelper.asmx")]
        public string JaizOpenDigitalBanking_BillsPaymentService_JaizHelper {
            get {
                return ((string)(this["JaizOpenDigitalBanking_BillsPaymentService_JaizHelper"]));
            }
        }
    }
}
