//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace JaizAgencyBanking.JaizInternal {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="processmessageSoap", Namespace="http://tempuri.org/")]
    public partial class processmessage : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ActivateSuspendedAccountOperationCompleted;
        
        private System.Threading.SendOrPostCallback getSessionIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback SuspendAccountOperationCompleted;
        
        private System.Threading.SendOrPostCallback FundTransferReversalOperationCompleted;
        
        private System.Threading.SendOrPostCallback LogforReversalOperationCompleted;
        
        private System.Threading.SendOrPostCallback fundtransfersingleitemOperationCompleted;
        
        private System.Threading.SendOrPostCallback UnblockAmountOperationCompleted;
        
        private System.Threading.SendOrPostCallback BlockAmountOperationCompleted;
        
        private System.Threading.SendOrPostCallback StopChequeOperationCompleted;
        
        private System.Threading.SendOrPostCallback ChequeLeaveStatusOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public processmessage() {
            this.Url = global::JaizAgencyBanking.Properties.Settings.Default.JaizOpenDigitalBanking_JaizInternal_processmessage;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ActivateSuspendedAccountCompletedEventHandler ActivateSuspendedAccountCompleted;
        
        /// <remarks/>
        public event getSessionIDCompletedEventHandler getSessionIDCompleted;
        
        /// <remarks/>
        public event SuspendAccountCompletedEventHandler SuspendAccountCompleted;
        
        /// <remarks/>
        public event FundTransferReversalCompletedEventHandler FundTransferReversalCompleted;
        
        /// <remarks/>
        public event LogforReversalCompletedEventHandler LogforReversalCompleted;
        
        /// <remarks/>
        public event fundtransfersingleitemCompletedEventHandler fundtransfersingleitemCompleted;
        
        /// <remarks/>
        public event UnblockAmountCompletedEventHandler UnblockAmountCompleted;
        
        /// <remarks/>
        public event BlockAmountCompletedEventHandler BlockAmountCompleted;
        
        /// <remarks/>
        public event StopChequeCompletedEventHandler StopChequeCompleted;
        
        /// <remarks/>
        public event ChequeLeaveStatusCompletedEventHandler ChequeLeaveStatusCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ActivateSuspendedAccount", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ActivateSuspendedAccount(string accountNumber) {
            object[] results = this.Invoke("ActivateSuspendedAccount", new object[] {
                        accountNumber});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ActivateSuspendedAccountAsync(string accountNumber) {
            this.ActivateSuspendedAccountAsync(accountNumber, null);
        }
        
        /// <remarks/>
        public void ActivateSuspendedAccountAsync(string accountNumber, object userState) {
            if ((this.ActivateSuspendedAccountOperationCompleted == null)) {
                this.ActivateSuspendedAccountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActivateSuspendedAccountOperationCompleted);
            }
            this.InvokeAsync("ActivateSuspendedAccount", new object[] {
                        accountNumber}, this.ActivateSuspendedAccountOperationCompleted, userState);
        }
        
        private void OnActivateSuspendedAccountOperationCompleted(object arg) {
            if ((this.ActivateSuspendedAccountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActivateSuspendedAccountCompleted(this, new ActivateSuspendedAccountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getSessionID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getSessionID() {
            object[] results = this.Invoke("getSessionID", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getSessionIDAsync() {
            this.getSessionIDAsync(null);
        }
        
        /// <remarks/>
        public void getSessionIDAsync(object userState) {
            if ((this.getSessionIDOperationCompleted == null)) {
                this.getSessionIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetSessionIDOperationCompleted);
            }
            this.InvokeAsync("getSessionID", new object[0], this.getSessionIDOperationCompleted, userState);
        }
        
        private void OngetSessionIDOperationCompleted(object arg) {
            if ((this.getSessionIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getSessionIDCompleted(this, new getSessionIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SuspendAccount", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SuspendAccount(string accountNumber) {
            object[] results = this.Invoke("SuspendAccount", new object[] {
                        accountNumber});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SuspendAccountAsync(string accountNumber) {
            this.SuspendAccountAsync(accountNumber, null);
        }
        
        /// <remarks/>
        public void SuspendAccountAsync(string accountNumber, object userState) {
            if ((this.SuspendAccountOperationCompleted == null)) {
                this.SuspendAccountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSuspendAccountOperationCompleted);
            }
            this.InvokeAsync("SuspendAccount", new object[] {
                        accountNumber}, this.SuspendAccountOperationCompleted, userState);
        }
        
        private void OnSuspendAccountOperationCompleted(object arg) {
            if ((this.SuspendAccountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SuspendAccountCompleted(this, new SuspendAccountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FundTransferReversal", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string FundTransferReversal(string sessionID) {
            object[] results = this.Invoke("FundTransferReversal", new object[] {
                        sessionID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void FundTransferReversalAsync(string sessionID) {
            this.FundTransferReversalAsync(sessionID, null);
        }
        
        /// <remarks/>
        public void FundTransferReversalAsync(string sessionID, object userState) {
            if ((this.FundTransferReversalOperationCompleted == null)) {
                this.FundTransferReversalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFundTransferReversalOperationCompleted);
            }
            this.InvokeAsync("FundTransferReversal", new object[] {
                        sessionID}, this.FundTransferReversalOperationCompleted, userState);
        }
        
        private void OnFundTransferReversalOperationCompleted(object arg) {
            if ((this.FundTransferReversalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FundTransferReversalCompleted(this, new FundTransferReversalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LogforReversal", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string LogforReversal(string sessionID) {
            object[] results = this.Invoke("LogforReversal", new object[] {
                        sessionID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LogforReversalAsync(string sessionID) {
            this.LogforReversalAsync(sessionID, null);
        }
        
        /// <remarks/>
        public void LogforReversalAsync(string sessionID, object userState) {
            if ((this.LogforReversalOperationCompleted == null)) {
                this.LogforReversalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLogforReversalOperationCompleted);
            }
            this.InvokeAsync("LogforReversal", new object[] {
                        sessionID}, this.LogforReversalOperationCompleted, userState);
        }
        
        private void OnLogforReversalOperationCompleted(object arg) {
            if ((this.LogforReversalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LogforReversalCompleted(this, new LogforReversalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/fundtransfersingleitem", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string fundtransfersingleitem(string xmlinput) {
            object[] results = this.Invoke("fundtransfersingleitem", new object[] {
                        xmlinput});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void fundtransfersingleitemAsync(string xmlinput) {
            this.fundtransfersingleitemAsync(xmlinput, null);
        }
        
        /// <remarks/>
        public void fundtransfersingleitemAsync(string xmlinput, object userState) {
            if ((this.fundtransfersingleitemOperationCompleted == null)) {
                this.fundtransfersingleitemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfundtransfersingleitemOperationCompleted);
            }
            this.InvokeAsync("fundtransfersingleitem", new object[] {
                        xmlinput}, this.fundtransfersingleitemOperationCompleted, userState);
        }
        
        private void OnfundtransfersingleitemOperationCompleted(object arg) {
            if ((this.fundtransfersingleitemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fundtransfersingleitemCompleted(this, new fundtransfersingleitemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UnblockAmount", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UnblockAmount(string reference, string amount) {
            object[] results = this.Invoke("UnblockAmount", new object[] {
                        reference,
                        amount});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UnblockAmountAsync(string reference, string amount) {
            this.UnblockAmountAsync(reference, amount, null);
        }
        
        /// <remarks/>
        public void UnblockAmountAsync(string reference, string amount, object userState) {
            if ((this.UnblockAmountOperationCompleted == null)) {
                this.UnblockAmountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUnblockAmountOperationCompleted);
            }
            this.InvokeAsync("UnblockAmount", new object[] {
                        reference,
                        amount}, this.UnblockAmountOperationCompleted, userState);
        }
        
        private void OnUnblockAmountOperationCompleted(object arg) {
            if ((this.UnblockAmountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UnblockAmountCompleted(this, new UnblockAmountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BlockAmount", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string BlockAmount(string accountNumber, string amount) {
            object[] results = this.Invoke("BlockAmount", new object[] {
                        accountNumber,
                        amount});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void BlockAmountAsync(string accountNumber, string amount) {
            this.BlockAmountAsync(accountNumber, amount, null);
        }
        
        /// <remarks/>
        public void BlockAmountAsync(string accountNumber, string amount, object userState) {
            if ((this.BlockAmountOperationCompleted == null)) {
                this.BlockAmountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBlockAmountOperationCompleted);
            }
            this.InvokeAsync("BlockAmount", new object[] {
                        accountNumber,
                        amount}, this.BlockAmountOperationCompleted, userState);
        }
        
        private void OnBlockAmountOperationCompleted(object arg) {
            if ((this.BlockAmountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BlockAmountCompleted(this, new BlockAmountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/StopCheque", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string StopCheque(string accountNumber, int chequeNumber) {
            object[] results = this.Invoke("StopCheque", new object[] {
                        accountNumber,
                        chequeNumber});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void StopChequeAsync(string accountNumber, int chequeNumber) {
            this.StopChequeAsync(accountNumber, chequeNumber, null);
        }
        
        /// <remarks/>
        public void StopChequeAsync(string accountNumber, int chequeNumber, object userState) {
            if ((this.StopChequeOperationCompleted == null)) {
                this.StopChequeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStopChequeOperationCompleted);
            }
            this.InvokeAsync("StopCheque", new object[] {
                        accountNumber,
                        chequeNumber}, this.StopChequeOperationCompleted, userState);
        }
        
        private void OnStopChequeOperationCompleted(object arg) {
            if ((this.StopChequeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StopChequeCompleted(this, new StopChequeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ChequeLeaveStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ChequeLeaveStatus(string accountNumber, int chequeNumber) {
            object[] results = this.Invoke("ChequeLeaveStatus", new object[] {
                        accountNumber,
                        chequeNumber});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ChequeLeaveStatusAsync(string accountNumber, int chequeNumber) {
            this.ChequeLeaveStatusAsync(accountNumber, chequeNumber, null);
        }
        
        /// <remarks/>
        public void ChequeLeaveStatusAsync(string accountNumber, int chequeNumber, object userState) {
            if ((this.ChequeLeaveStatusOperationCompleted == null)) {
                this.ChequeLeaveStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnChequeLeaveStatusOperationCompleted);
            }
            this.InvokeAsync("ChequeLeaveStatus", new object[] {
                        accountNumber,
                        chequeNumber}, this.ChequeLeaveStatusOperationCompleted, userState);
        }
        
        private void OnChequeLeaveStatusOperationCompleted(object arg) {
            if ((this.ChequeLeaveStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ChequeLeaveStatusCompleted(this, new ChequeLeaveStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void ActivateSuspendedAccountCompletedEventHandler(object sender, ActivateSuspendedAccountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ActivateSuspendedAccountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ActivateSuspendedAccountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void getSessionIDCompletedEventHandler(object sender, getSessionIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getSessionIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getSessionIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void SuspendAccountCompletedEventHandler(object sender, SuspendAccountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SuspendAccountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SuspendAccountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void FundTransferReversalCompletedEventHandler(object sender, FundTransferReversalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FundTransferReversalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FundTransferReversalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void LogforReversalCompletedEventHandler(object sender, LogforReversalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LogforReversalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LogforReversalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void fundtransfersingleitemCompletedEventHandler(object sender, fundtransfersingleitemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fundtransfersingleitemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal fundtransfersingleitemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void UnblockAmountCompletedEventHandler(object sender, UnblockAmountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UnblockAmountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UnblockAmountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void BlockAmountCompletedEventHandler(object sender, BlockAmountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BlockAmountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BlockAmountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void StopChequeCompletedEventHandler(object sender, StopChequeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StopChequeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal StopChequeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void ChequeLeaveStatusCompletedEventHandler(object sender, ChequeLeaveStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChequeLeaveStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ChequeLeaveStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591