//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace JaizAgencyBanking.NewNIP {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="processmessageSoap", Namespace="http://tempuri.org/")]
    public partial class processmessage : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback nameenquirysingleitemOperationCompleted;
        
        private System.Threading.SendOrPostCallback fundtransfersingleitem_dcOperationCompleted;
        
        private System.Threading.SendOrPostCallback txnstatusquerysingleitemOperationCompleted;
        
        private System.Threading.SendOrPostCallback newNIPTSQOperationCompleted;
        
        private System.Threading.SendOrPostCallback getChargesOperationCompleted;
        
        private System.Threading.SendOrPostCallback AccountStatementOperationCompleted;
        
        private System.Threading.SendOrPostCallback FundTransferOperationCompleted;
        
        private System.Threading.SendOrPostCallback FundTransferStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback FundTransferReversalOperationCompleted;
        
        private System.Threading.SendOrPostCallback NameEnquiryInhouseOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConfirmtxnstatusquerysingleitemOperationCompleted;
        
        private System.Threading.SendOrPostCallback getSessionIDExistenceOperationCompleted;
        
        private System.Threading.SendOrPostCallback SSMEncryptDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback SSMDecryptDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback SSMHashwithSHAOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public processmessage() {
            this.Url = global::JaizAgencyBanking.Properties.Settings.Default.JaizOpenDigitalBanking_JaizNIBSSInterface_processmessage;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event nameenquirysingleitemCompletedEventHandler nameenquirysingleitemCompleted;
        
        /// <remarks/>
        public event fundtransfersingleitem_dcCompletedEventHandler fundtransfersingleitem_dcCompleted;
        
        /// <remarks/>
        public event txnstatusquerysingleitemCompletedEventHandler txnstatusquerysingleitemCompleted;
        
        /// <remarks/>
        public event newNIPTSQCompletedEventHandler newNIPTSQCompleted;
        
        /// <remarks/>
        public event getChargesCompletedEventHandler getChargesCompleted;
        
        /// <remarks/>
        public event AccountStatementCompletedEventHandler AccountStatementCompleted;
        
        /// <remarks/>
        public event FundTransferCompletedEventHandler FundTransferCompleted;
        
        /// <remarks/>
        public event FundTransferStatusCompletedEventHandler FundTransferStatusCompleted;
        
        /// <remarks/>
        public event FundTransferReversalCompletedEventHandler FundTransferReversalCompleted;
        
        /// <remarks/>
        public event NameEnquiryInhouseCompletedEventHandler NameEnquiryInhouseCompleted;
        
        /// <remarks/>
        public event ConfirmtxnstatusquerysingleitemCompletedEventHandler ConfirmtxnstatusquerysingleitemCompleted;
        
        /// <remarks/>
        public event getSessionIDExistenceCompletedEventHandler getSessionIDExistenceCompleted;
        
        /// <remarks/>
        public event SSMEncryptDataCompletedEventHandler SSMEncryptDataCompleted;
        
        /// <remarks/>
        public event SSMDecryptDataCompletedEventHandler SSMDecryptDataCompleted;
        
        /// <remarks/>
        public event SSMHashwithSHACompletedEventHandler SSMHashwithSHACompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/nameenquirysingleitem", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string nameenquirysingleitem(string inputXml) {
            object[] results = this.Invoke("nameenquirysingleitem", new object[] {
                        inputXml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void nameenquirysingleitemAsync(string inputXml) {
            this.nameenquirysingleitemAsync(inputXml, null);
        }
        
        /// <remarks/>
        public void nameenquirysingleitemAsync(string inputXml, object userState) {
            if ((this.nameenquirysingleitemOperationCompleted == null)) {
                this.nameenquirysingleitemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnnameenquirysingleitemOperationCompleted);
            }
            this.InvokeAsync("nameenquirysingleitem", new object[] {
                        inputXml}, this.nameenquirysingleitemOperationCompleted, userState);
        }
        
        private void OnnameenquirysingleitemOperationCompleted(object arg) {
            if ((this.nameenquirysingleitemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.nameenquirysingleitemCompleted(this, new nameenquirysingleitemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/fundtransfersingleitem_dc", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string fundtransfersingleitem_dc(string inputXml) {
            object[] results = this.Invoke("fundtransfersingleitem_dc", new object[] {
                        inputXml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void fundtransfersingleitem_dcAsync(string inputXml) {
            this.fundtransfersingleitem_dcAsync(inputXml, null);
        }
        
        /// <remarks/>
        public void fundtransfersingleitem_dcAsync(string inputXml, object userState) {
            if ((this.fundtransfersingleitem_dcOperationCompleted == null)) {
                this.fundtransfersingleitem_dcOperationCompleted = new System.Threading.SendOrPostCallback(this.Onfundtransfersingleitem_dcOperationCompleted);
            }
            this.InvokeAsync("fundtransfersingleitem_dc", new object[] {
                        inputXml}, this.fundtransfersingleitem_dcOperationCompleted, userState);
        }
        
        private void Onfundtransfersingleitem_dcOperationCompleted(object arg) {
            if ((this.fundtransfersingleitem_dcCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fundtransfersingleitem_dcCompleted(this, new fundtransfersingleitem_dcCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/txnstatusquerysingleitem", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string txnstatusquerysingleitem(string inputXml) {
            object[] results = this.Invoke("txnstatusquerysingleitem", new object[] {
                        inputXml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void txnstatusquerysingleitemAsync(string inputXml) {
            this.txnstatusquerysingleitemAsync(inputXml, null);
        }
        
        /// <remarks/>
        public void txnstatusquerysingleitemAsync(string inputXml, object userState) {
            if ((this.txnstatusquerysingleitemOperationCompleted == null)) {
                this.txnstatusquerysingleitemOperationCompleted = new System.Threading.SendOrPostCallback(this.OntxnstatusquerysingleitemOperationCompleted);
            }
            this.InvokeAsync("txnstatusquerysingleitem", new object[] {
                        inputXml}, this.txnstatusquerysingleitemOperationCompleted, userState);
        }
        
        private void OntxnstatusquerysingleitemOperationCompleted(object arg) {
            if ((this.txnstatusquerysingleitemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.txnstatusquerysingleitemCompleted(this, new txnstatusquerysingleitemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/newNIPTSQ", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string newNIPTSQ(string inputXml) {
            object[] results = this.Invoke("newNIPTSQ", new object[] {
                        inputXml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void newNIPTSQAsync(string inputXml) {
            this.newNIPTSQAsync(inputXml, null);
        }
        
        /// <remarks/>
        public void newNIPTSQAsync(string inputXml, object userState) {
            if ((this.newNIPTSQOperationCompleted == null)) {
                this.newNIPTSQOperationCompleted = new System.Threading.SendOrPostCallback(this.OnnewNIPTSQOperationCompleted);
            }
            this.InvokeAsync("newNIPTSQ", new object[] {
                        inputXml}, this.newNIPTSQOperationCompleted, userState);
        }
        
        private void OnnewNIPTSQOperationCompleted(object arg) {
            if ((this.newNIPTSQCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.newNIPTSQCompleted(this, new newNIPTSQCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getCharges", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public double getCharges(double amount) {
            object[] results = this.Invoke("getCharges", new object[] {
                        amount});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void getChargesAsync(double amount) {
            this.getChargesAsync(amount, null);
        }
        
        /// <remarks/>
        public void getChargesAsync(double amount, object userState) {
            if ((this.getChargesOperationCompleted == null)) {
                this.getChargesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetChargesOperationCompleted);
            }
            this.InvokeAsync("getCharges", new object[] {
                        amount}, this.getChargesOperationCompleted, userState);
        }
        
        private void OngetChargesOperationCompleted(object arg) {
            if ((this.getChargesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getChargesCompleted(this, new getChargesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AccountStatement", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AccountStatement(string inputXml) {
            object[] results = this.Invoke("AccountStatement", new object[] {
                        inputXml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AccountStatementAsync(string inputXml) {
            this.AccountStatementAsync(inputXml, null);
        }
        
        /// <remarks/>
        public void AccountStatementAsync(string inputXml, object userState) {
            if ((this.AccountStatementOperationCompleted == null)) {
                this.AccountStatementOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAccountStatementOperationCompleted);
            }
            this.InvokeAsync("AccountStatement", new object[] {
                        inputXml}, this.AccountStatementOperationCompleted, userState);
        }
        
        private void OnAccountStatementOperationCompleted(object arg) {
            if ((this.AccountStatementCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AccountStatementCompleted(this, new AccountStatementCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FundTransfer", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string FundTransfer(string inputXml) {
            object[] results = this.Invoke("FundTransfer", new object[] {
                        inputXml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void FundTransferAsync(string inputXml) {
            this.FundTransferAsync(inputXml, null);
        }
        
        /// <remarks/>
        public void FundTransferAsync(string inputXml, object userState) {
            if ((this.FundTransferOperationCompleted == null)) {
                this.FundTransferOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFundTransferOperationCompleted);
            }
            this.InvokeAsync("FundTransfer", new object[] {
                        inputXml}, this.FundTransferOperationCompleted, userState);
        }
        
        private void OnFundTransferOperationCompleted(object arg) {
            if ((this.FundTransferCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FundTransferCompleted(this, new FundTransferCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FundTransferStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string FundTransferStatus(string inputXml) {
            object[] results = this.Invoke("FundTransferStatus", new object[] {
                        inputXml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void FundTransferStatusAsync(string inputXml) {
            this.FundTransferStatusAsync(inputXml, null);
        }
        
        /// <remarks/>
        public void FundTransferStatusAsync(string inputXml, object userState) {
            if ((this.FundTransferStatusOperationCompleted == null)) {
                this.FundTransferStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFundTransferStatusOperationCompleted);
            }
            this.InvokeAsync("FundTransferStatus", new object[] {
                        inputXml}, this.FundTransferStatusOperationCompleted, userState);
        }
        
        private void OnFundTransferStatusOperationCompleted(object arg) {
            if ((this.FundTransferStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FundTransferStatusCompleted(this, new FundTransferStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FundTransferReversal", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string FundTransferReversal(string inputXml) {
            object[] results = this.Invoke("FundTransferReversal", new object[] {
                        inputXml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void FundTransferReversalAsync(string inputXml) {
            this.FundTransferReversalAsync(inputXml, null);
        }
        
        /// <remarks/>
        public void FundTransferReversalAsync(string inputXml, object userState) {
            if ((this.FundTransferReversalOperationCompleted == null)) {
                this.FundTransferReversalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFundTransferReversalOperationCompleted);
            }
            this.InvokeAsync("FundTransferReversal", new object[] {
                        inputXml}, this.FundTransferReversalOperationCompleted, userState);
        }
        
        private void OnFundTransferReversalOperationCompleted(object arg) {
            if ((this.FundTransferReversalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FundTransferReversalCompleted(this, new FundTransferReversalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/NameEnquiryInhouse", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string NameEnquiryInhouse(string nuban) {
            object[] results = this.Invoke("NameEnquiryInhouse", new object[] {
                        nuban});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void NameEnquiryInhouseAsync(string nuban) {
            this.NameEnquiryInhouseAsync(nuban, null);
        }
        
        /// <remarks/>
        public void NameEnquiryInhouseAsync(string nuban, object userState) {
            if ((this.NameEnquiryInhouseOperationCompleted == null)) {
                this.NameEnquiryInhouseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNameEnquiryInhouseOperationCompleted);
            }
            this.InvokeAsync("NameEnquiryInhouse", new object[] {
                        nuban}, this.NameEnquiryInhouseOperationCompleted, userState);
        }
        
        private void OnNameEnquiryInhouseOperationCompleted(object arg) {
            if ((this.NameEnquiryInhouseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NameEnquiryInhouseCompleted(this, new NameEnquiryInhouseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Confirmtxnstatusquerysingleitem", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Confirmtxnstatusquerysingleitem(string inputXml) {
            object[] results = this.Invoke("Confirmtxnstatusquerysingleitem", new object[] {
                        inputXml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConfirmtxnstatusquerysingleitemAsync(string inputXml) {
            this.ConfirmtxnstatusquerysingleitemAsync(inputXml, null);
        }
        
        /// <remarks/>
        public void ConfirmtxnstatusquerysingleitemAsync(string inputXml, object userState) {
            if ((this.ConfirmtxnstatusquerysingleitemOperationCompleted == null)) {
                this.ConfirmtxnstatusquerysingleitemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConfirmtxnstatusquerysingleitemOperationCompleted);
            }
            this.InvokeAsync("Confirmtxnstatusquerysingleitem", new object[] {
                        inputXml}, this.ConfirmtxnstatusquerysingleitemOperationCompleted, userState);
        }
        
        private void OnConfirmtxnstatusquerysingleitemOperationCompleted(object arg) {
            if ((this.ConfirmtxnstatusquerysingleitemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConfirmtxnstatusquerysingleitemCompleted(this, new ConfirmtxnstatusquerysingleitemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getSessionIDExistence", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getSessionIDExistence(string sessionID, string amount, string creditAccount, string debitAccount) {
            object[] results = this.Invoke("getSessionIDExistence", new object[] {
                        sessionID,
                        amount,
                        creditAccount,
                        debitAccount});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getSessionIDExistenceAsync(string sessionID, string amount, string creditAccount, string debitAccount) {
            this.getSessionIDExistenceAsync(sessionID, amount, creditAccount, debitAccount, null);
        }
        
        /// <remarks/>
        public void getSessionIDExistenceAsync(string sessionID, string amount, string creditAccount, string debitAccount, object userState) {
            if ((this.getSessionIDExistenceOperationCompleted == null)) {
                this.getSessionIDExistenceOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetSessionIDExistenceOperationCompleted);
            }
            this.InvokeAsync("getSessionIDExistence", new object[] {
                        sessionID,
                        amount,
                        creditAccount,
                        debitAccount}, this.getSessionIDExistenceOperationCompleted, userState);
        }
        
        private void OngetSessionIDExistenceOperationCompleted(object arg) {
            if ((this.getSessionIDExistenceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getSessionIDExistenceCompleted(this, new getSessionIDExistenceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SSMEncryptData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SSMEncryptData(string input) {
            object[] results = this.Invoke("SSMEncryptData", new object[] {
                        input});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SSMEncryptDataAsync(string input) {
            this.SSMEncryptDataAsync(input, null);
        }
        
        /// <remarks/>
        public void SSMEncryptDataAsync(string input, object userState) {
            if ((this.SSMEncryptDataOperationCompleted == null)) {
                this.SSMEncryptDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSSMEncryptDataOperationCompleted);
            }
            this.InvokeAsync("SSMEncryptData", new object[] {
                        input}, this.SSMEncryptDataOperationCompleted, userState);
        }
        
        private void OnSSMEncryptDataOperationCompleted(object arg) {
            if ((this.SSMEncryptDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SSMEncryptDataCompleted(this, new SSMEncryptDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SSMDecryptData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SSMDecryptData(string input) {
            object[] results = this.Invoke("SSMDecryptData", new object[] {
                        input});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SSMDecryptDataAsync(string input) {
            this.SSMDecryptDataAsync(input, null);
        }
        
        /// <remarks/>
        public void SSMDecryptDataAsync(string input, object userState) {
            if ((this.SSMDecryptDataOperationCompleted == null)) {
                this.SSMDecryptDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSSMDecryptDataOperationCompleted);
            }
            this.InvokeAsync("SSMDecryptData", new object[] {
                        input}, this.SSMDecryptDataOperationCompleted, userState);
        }
        
        private void OnSSMDecryptDataOperationCompleted(object arg) {
            if ((this.SSMDecryptDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SSMDecryptDataCompleted(this, new SSMDecryptDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SSMHashwithSHA", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SSMHashwithSHA(string input) {
            object[] results = this.Invoke("SSMHashwithSHA", new object[] {
                        input});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SSMHashwithSHAAsync(string input) {
            this.SSMHashwithSHAAsync(input, null);
        }
        
        /// <remarks/>
        public void SSMHashwithSHAAsync(string input, object userState) {
            if ((this.SSMHashwithSHAOperationCompleted == null)) {
                this.SSMHashwithSHAOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSSMHashwithSHAOperationCompleted);
            }
            this.InvokeAsync("SSMHashwithSHA", new object[] {
                        input}, this.SSMHashwithSHAOperationCompleted, userState);
        }
        
        private void OnSSMHashwithSHAOperationCompleted(object arg) {
            if ((this.SSMHashwithSHACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SSMHashwithSHACompleted(this, new SSMHashwithSHACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void nameenquirysingleitemCompletedEventHandler(object sender, nameenquirysingleitemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class nameenquirysingleitemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal nameenquirysingleitemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void fundtransfersingleitem_dcCompletedEventHandler(object sender, fundtransfersingleitem_dcCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fundtransfersingleitem_dcCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal fundtransfersingleitem_dcCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void txnstatusquerysingleitemCompletedEventHandler(object sender, txnstatusquerysingleitemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class txnstatusquerysingleitemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal txnstatusquerysingleitemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void newNIPTSQCompletedEventHandler(object sender, newNIPTSQCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class newNIPTSQCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal newNIPTSQCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void getChargesCompletedEventHandler(object sender, getChargesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getChargesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getChargesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void AccountStatementCompletedEventHandler(object sender, AccountStatementCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AccountStatementCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AccountStatementCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void FundTransferCompletedEventHandler(object sender, FundTransferCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FundTransferCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FundTransferCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void FundTransferStatusCompletedEventHandler(object sender, FundTransferStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FundTransferStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FundTransferStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void FundTransferReversalCompletedEventHandler(object sender, FundTransferReversalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FundTransferReversalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FundTransferReversalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void NameEnquiryInhouseCompletedEventHandler(object sender, NameEnquiryInhouseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NameEnquiryInhouseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NameEnquiryInhouseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void ConfirmtxnstatusquerysingleitemCompletedEventHandler(object sender, ConfirmtxnstatusquerysingleitemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConfirmtxnstatusquerysingleitemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConfirmtxnstatusquerysingleitemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void getSessionIDExistenceCompletedEventHandler(object sender, getSessionIDExistenceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getSessionIDExistenceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getSessionIDExistenceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void SSMEncryptDataCompletedEventHandler(object sender, SSMEncryptDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SSMEncryptDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SSMEncryptDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void SSMDecryptDataCompletedEventHandler(object sender, SSMDecryptDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SSMDecryptDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SSMDecryptDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void SSMHashwithSHACompletedEventHandler(object sender, SSMHashwithSHACompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SSMHashwithSHACompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SSMHashwithSHACompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591